import = ["~/.config/alacritty/themes/themes/tokyo-night-dark.toml"]
[env]
TERM = "xterm-256color"

[window]
padding.x = 5 
padding.y = 5

decorations = "Buttonless"
opacity = 1
blur = true

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"
size = 14

