import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
[env]
TERM = "xterm-256color"

[window]
padding.x = 5 
padding.y = 5

decorations = "Buttonless"
opacity = 1
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 19

